### ISSUE TITLE
Add "Event" button in the SCS homepage header.

### ISSUE THREAD

**Issue by manuela-urban** [SovereignCloudStack/website#762]
Under "Events" our own events should be announced and linked if necessary. Furthermore, conference participations of our project team members and community members on SCS topics could be made visible here ("Where can you meet SCS project team members and contributors?" or similar).

**Comment by garloff** [comment]
We have an Events page and a menu bar entry for it since #763.
Next step is to fill the Events page with more content:
- [ ] The page could advertize the next SCS summit more prominently.
- [ ] We should proabably have a yaml with events where we participate and generate content from it to be listed on the events page ...

**Comment by manuela-urban** [comment]
Thanks for having done!
